fail_fast: false
repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      args: [--line-length=100, --safe]
      python_version: python3.12
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: debug-statements  # check for existence of debug statements
      - id: flake8
        name: flake8
        entry: flake8
